import { BadgeColor } from '../components/ui';

export type SkillBranchId = 'hvac' | 'cyber' | 'mechanical';

export interface SkillNode {
  id: string;
  branch: SkillBranchId;
  name: string;
  titleIndo: string;
  tier: 1 | 2 | 3;
  branchPath: 'core' | 'path_a' | 'path_b';
  xpCost: number;
  levelRequired: number;
  prerequisiteId: string | null;
  icon: string;
  accent: BadgeColor;
  summary: string;
  tacticalPerks: string[];
  unlockedContracts: string[];
  gridX: number; // percentage (0-100)
  gridY: number; // percentage (0-100)
}

export interface SkillBranch {
  id: SkillBranchId;
  name: string;
  subtitle: string;
  accent: BadgeColor;
  icon: string;
  description: string;
  nodes: SkillNode[];
}

export const SKILL_BRANCHES: SkillBranch[] = [
  {
    id: 'hvac',
    name: 'HVAC & THERMAL DYNAMICS',
    subtitle: 'Teknisi AC Dasar ➔ Spesialis Pendingin Komersial & Chiller Industri',
    accent: 'cyan',
    icon: 'snow-outline',
    description: 'Pohon keahlian spesialisasi pendingin udara mulai dari unit split hunian, VRF multi-gedung, hingga chiller amonia industri 5MW.',
    nodes: [
      {
        id: 'hvac_1',
        branch: 'hvac',
        name: 'Residential Split AC Technician',
        titleIndo: 'Teknisi AC Split Residensial',
        tier: 1,
        branchPath: 'core',
        xpCost: 0, // baseline
        levelRequired: 1,
        prerequisiteId: null,
        icon: 'thermometer-outline',
        accent: 'cyan',
        summary: 'Pemeriksaan tekanan freon R32, pembersihan evaporator, dan instalasi dasar AC split hunian.',
        tacticalPerks: ['Akses Misi Residential Split AC', '+5% Akurasi Diagnostik Freon'],
        unlockedContracts: ['Cuci & Servis AC Hunian 0.5-2 PK', 'Pengisian Freon R32 & R410A'],
        gridX: 50,
        gridY: 15,
      },
      // Path A: Heavy Commercial / Chiller
      {
        id: 'hvac_2a',
        branch: 'hvac',
        name: 'Commercial VRF Multi-Split Specialist',
        titleIndo: 'Spesialis Pendingin Komersial & VRF',
        tier: 2,
        branchPath: 'path_a',
        xpCost: 1200,
        levelRequired: 5,
        prerequisiteId: 'hvac_1',
        icon: 'business-outline',
        accent: 'cyan',
        summary: 'Instalasi pipa refnet branch, kalibrasi ducting, dan manajemen aliran refrigeran pada gedung perkantoran.',
        tacticalPerks: ['Akses Misi Komersial Gedung B2B', '+15% Escrow Reward Multiplier', 'Membuka Slot Bimbingan 1 Sidekick'],
        unlockedContracts: ['Overhaul AC Sentral Perkantoran Sudirman', 'Kalibrasi VRF Gedung 10 Lantai'],
        gridX: 25,
        gridY: 50,
      },
      {
        id: 'hvac_3a',
        branch: 'hvac',
        name: 'Industrial Chiller & Cryo Master',
        titleIndo: 'Master Chiller & Cold Storage Industri',
        tier: 3,
        branchPath: 'path_a',
        xpCost: 2500,
        levelRequired: 12,
        prerequisiteId: 'hvac_2a',
        icon: 'flame-outline',
        accent: 'crimson',
        summary: 'Pemeliharaan berat chiller amonia, evaporator turbin, dan pusat logistik rantai beku berdaya megawatt.',
        tacticalPerks: ['Akses Kontrak Korporat Tier-A (Rp 1.5M+)', '+25% Hero Coins Multiplier', 'Gelar: Master Thermal Engineer'],
        unlockedContracts: ['Overhaul Chiller Logistik Cold Storage 5MW', 'Emergency Compressor Rebuild Pelabuhan'],
        gridX: 25,
        gridY: 85,
      },
      // Path B: Smart Building & BMS Automation
      {
        id: 'hvac_2b',
        branch: 'hvac',
        name: 'Modbus & BMS Climate Integrator',
        titleIndo: 'Integrator Otomasi BMS & Modbus',
        tier: 2,
        branchPath: 'path_b',
        xpCost: 1300,
        levelRequired: 6,
        prerequisiteId: 'hvac_1',
        icon: 'hardware-chip-outline',
        accent: 'amber',
        summary: 'Integrasi sensor suhu IoT, Modbus RTU controller, dan otomasi penghematan energi HVAC cerdas.',
        tacticalPerks: ['Akses Diagnostik Smart Sensor AR', '+10% Efisiensi Waktu Misi', 'Telemetry AR Overlay Diaktifkan'],
        unlockedContracts: ['Integrasi BMS Sensor Suhu Smart Office', 'Kalibrasi Sensor Kelembapan Server Room'],
        gridX: 75,
        gridY: 50,
      },
      {
        id: 'hvac_3b',
        branch: 'hvac',
        name: 'Cleanroom & Precision Climate Architect',
        titleIndo: 'Arsitek Presisi HVAC Farmasi & Data Center',
        tier: 3,
        branchPath: 'path_b',
        xpCost: 2800,
        levelRequired: 14,
        prerequisiteId: 'hvac_2b',
        icon: 'nuclear-outline',
        accent: 'purple',
        summary: 'Sertifikasi HVAC cleanroom ISO Class 5 untuk laboratorium medis, pabrik semikonduktor, dan hyperscale data center.',
        tacticalPerks: ['Akses Kontrak Data Center Tier-IV (Rp 3M+)', 'Prioritas Gate Break Dispatch +50%', 'Gelar: Precision Climate Architect'],
        unlockedContracts: ['Sterilisasi Cleanroom Lab Biofarma', 'Hyperscale Data Center Precision Cooling'],
        gridX: 75,
        gridY: 85,
      },
    ],
  },
  {
    id: 'cyber',
    name: 'CYBERSECURITY & IT INFRASTRUCTURE',
    subtitle: 'Teknisi IT Hardware ➔ Enterprise Network & Threat Architect',
    accent: 'purple',
    icon: 'shield-checkmark-outline',
    description: 'Pohon keahlian infrastruktur data, switching managed 10G, penetrasi jaringan, dan pertahanan siber tier-enterprise.',
    nodes: [
      {
        id: 'cyber_1',
        branch: 'cyber',
        name: 'Hardware & Local Network Technician',
        titleIndo: 'Teknisi IT & Jaringan Lokal',
        tier: 1,
        branchPath: 'core',
        xpCost: 0,
        levelRequired: 1,
        prerequisiteId: null,
        icon: 'desktop-outline',
        accent: 'cyan',
        summary: 'Troubleshooting hardware PC, crimping kabel UTP Cat6, dan setup router gateway kantor kecil.',
        tacticalPerks: ['Akses Misi Setup PC & LAN UMKM', 'Diagnostik Hardware Cepat'],
        unlockedContracts: ['Setup Jaringan Kantor 15 Workstation', 'Perakitan Server Kasir Point of Sale'],
        gridX: 50,
        gridY: 15,
      },
      // Path A: Enterprise Networks & Cloud
      {
        id: 'cyber_2a',
        branch: 'cyber',
        name: 'Enterprise Switch & Fiber Engineer',
        titleIndo: 'Engineer Managed Switch & Fiber 10G',
        tier: 2,
        branchPath: 'path_a',
        xpCost: 1400,
        levelRequired: 6,
        prerequisiteId: 'cyber_1',
        icon: 'server-outline',
        accent: 'purple',
        summary: 'Konfigurasi switch L3 managed, fiber optic fusion splicing, VLAN trunking, dan manajemen server rack.',
        tacticalPerks: ['Akses Misi Data Center Colocation', '+20% Escrow Reward Multiplier', 'Hak Bimbingan 1 Sidekick IT'],
        unlockedContracts: ['Fiber Optic Splicing Menara Sudirman', 'VLAN Trunking Jaringan Bank Cabang'],
        gridX: 25,
        gridY: 50,
      },
      {
        id: 'cyber_3a',
        branch: 'cyber',
        name: 'Zero-Trust & Cyber Threat Architect',
        titleIndo: 'Arsitek Zero-Trust & Mitigasi Ancaman',
        tier: 3,
        branchPath: 'path_a',
        xpCost: 3000,
        levelRequired: 14,
        prerequisiteId: 'cyber_2a',
        icon: 'lock-closed-outline',
        accent: 'purple',
        summary: 'Zero-Trust network containment, forensik insiden siber, enkripsi database, dan mitigasi serangan DDoS kritis.',
        tacticalPerks: ['Akses Kontrak Korporat Rahasia (Rp 3M+)', 'Gate Break Network Priority Dispatch', 'Gelar: Elite Security Architect'],
        unlockedContracts: ['Mitigasi Server Crash Bank Sentral', 'Zero-Trust Audit Corporate Executive Array'],
        gridX: 25,
        gridY: 85,
      },
      // Path B: IoT Firmware & SCADA Defense
      {
        id: 'cyber_2b',
        branch: 'cyber',
        name: 'IoT Gateway & Embedded Telemetry Tech',
        titleIndo: 'Teknisi IoT Gateway & Embedded Firmware',
        tier: 2,
        branchPath: 'path_b',
        xpCost: 1500,
        levelRequired: 7,
        prerequisiteId: 'cyber_1',
        icon: 'radio-outline',
        accent: 'emerald',
        summary: 'Pemrograman microcontroller ESP32/ARM, MQTT bridge, dan telemetri sensor industri jarak jauh.',
        tacticalPerks: ['Akses Misi IoT Telemetri Pabrik', '+15% Akurasi Telemetri', 'Bypass Jalur Diagnostik Jarak Jauh'],
        unlockedContracts: ['Deploy Sensor IoT Pabrik Otomotif', 'Firmware Patch Gateway Logistik'],
        gridX: 75,
        gridY: 50,
      },
      {
        id: 'cyber_3b',
        branch: 'cyber',
        name: 'Critical SCADA & Industrial Grid Defender',
        titleIndo: 'Spesialis Keamanan SCADA & Infrastruktur Kritis',
        tier: 3,
        branchPath: 'path_b',
        xpCost: 3200,
        levelRequired: 15,
        prerequisiteId: 'cyber_2b',
        icon: 'flash-outline',
        accent: 'crimson',
        summary: 'Pertahanan siber sistem kendali industri PLC/SCADA pembangkit listrik, bandara, dan fasilitas utilitas negara.',
        tacticalPerks: ['Akses Kontrak BUMN Infrastruktur Vital', '+30% Hero Coins Reward', 'Gelar: Industrial Grid Defender'],
        unlockedContracts: ['Audit Keamanan SCADA Gardu Induk 150kV', 'Firewall Air-Gap Kendali Runway Bandara'],
        gridX: 75,
        gridY: 85,
      },
    ],
  },
  {
    id: 'mechanical',
    name: 'AUTOMOTIVE & HEAVY RECOVERY',
    subtitle: 'Mekanik Darurat Jalan Raya ➔ Heavy Fleet Hydraulics & EV Systems',
    accent: 'amber',
    icon: 'car-outline',
    description: 'Pohon keahlian mekanikal darurat jalan raya, evakuasi derek cepat tol, hidrolik crane industri, dan teknologi EV tinggi.',
    nodes: [
      {
        id: 'mech_1',
        branch: 'mechanical',
        name: 'Emergency Roadside Technician',
        titleIndo: 'Teknisi Darurat Jalan Raya',
        tier: 1,
        branchPath: 'core',
        xpCost: 0,
        levelRequired: 1,
        prerequisiteId: null,
        icon: 'battery-charging-outline',
        accent: 'cyan',
        summary: 'Penanganan jumper aki mati, penggantian ban darurat, dan diagnosa awal alternator starter mobil.',
        tacticalPerks: ['Akses Misi Roadside Assistance', 'Toolkit Darurat Jalan Protokol'],
        unlockedContracts: ['Jumpstart Aki Mogok Basement Parkir', 'Ganti Ban Darurat Jalur Protokol'],
        gridX: 50,
        gridY: 15,
      },
      // Path A: Heavy Hydraulics & Recovery
      {
        id: 'mech_2a',
        branch: 'mechanical',
        name: 'Highway Towing & Flatbed Specialist',
        titleIndo: 'Spesialis Evakuasi Derek & Flatbed Jalan Tol',
        tier: 2,
        branchPath: 'path_a',
        xpCost: 1400,
        levelRequired: 6,
        prerequisiteId: 'mech_1',
        icon: 'speedometer-outline',
        accent: 'amber',
        summary: 'Towing derek flatbed darurat kecepatan tinggi pada jalur bebas hambatan tanpa merusak sistem transmisi.',
        tacticalPerks: ['Akses Misi Evakuasi Jalan Tol KM 10-50', 'Prioritas Pengawalan Lalu Lintas', '+15% Escrow Payout'],
        unlockedContracts: ['Emergency Highway Towing Bypass', 'Evakuasi Transmisi Terkunci Jalur Cepat'],
        gridX: 25,
        gridY: 50,
      },
      {
        id: 'mech_3a',
        branch: 'mechanical',
        name: 'Heavy Fleet Hydraulics & Crane Master',
        titleIndo: 'Master Hidrolik Alat Berat & Derek Crane',
        tier: 3,
        branchPath: 'path_a',
        xpCost: 2900,
        levelRequired: 13,
        prerequisiteId: 'mech_2a',
        icon: 'construct-outline',
        accent: 'crimson',
        summary: 'Overhaul pompa hidrolik tekanan tinggi, crane pelabuhan dermaga, dan perbaikan mesin diesel alat berat.',
        tacticalPerks: ['Akses Kontrak Proyek Pelabuhan & Tambang', '+30% Hero Coins Multiplier', 'Gelar: Heavy Fleet Commander'],
        unlockedContracts: ['Overhaul Hidrolik Crane Dermaga Tanjung Priok', 'Perbaikan Diesel Generator 1000kVA'],
        gridX: 25,
        gridY: 85,
      },
      // Path B: EV High-Voltage & Powertrain
      {
        id: 'mech_2b',
        branch: 'mechanical',
        name: 'EV High-Voltage & Inverter Specialist',
        titleIndo: 'Spesialis Inverter & Baterai Mobil Listrik (EV)',
        tier: 2,
        branchPath: 'path_b',
        xpCost: 1600,
        levelRequired: 7,
        prerequisiteId: 'mech_1',
        icon: 'flash-outline',
        accent: 'emerald',
        summary: 'Diagnostik baterai lithium 400V/800V, isolasi inverter motor listrik, dan penanganan darurat kabel oranye EV.',
        tacticalPerks: ['Akses Misi Kendaraan Listrik (EV)', '+20% Escrow Bounty Multiplier', 'Sertifikasi Tegangan Tinggi 800V'],
        unlockedContracts: ['Emergency Isolation Inverter EV Mogok', 'Diagnostik Degradasi BMS Battery Pack EV'],
        gridX: 75,
        gridY: 50,
      },
      {
        id: 'mech_3b',
        branch: 'mechanical',
        name: 'Apex Powertrain & Autonomous Fleet Master',
        titleIndo: 'Master Powertrain & Armada Otonom',
        tier: 3,
        branchPath: 'path_b',
        xpCost: 3100,
        levelRequired: 14,
        prerequisiteId: 'mech_2b',
        icon: 'hardware-chip-outline',
        accent: 'purple',
        summary: 'Kalibrasi radar LiDAR armada otonom, tuning ECU performa tinggi, dan overhaul motor ganda kendaraan industri.',
        tacticalPerks: ['Akses Kontrak Armada Otonom Korporat', '+35% Hero Coins Multiplier', 'Gelar: Apex Powertrain Master'],
        unlockedContracts: ['Kalibrasi Sensor LiDAR Armada Truk Otonom', 'Rebuild Dual-Motor Inverter Supercar EV'],
        gridX: 75,
        gridY: 85,
      },
    ],
  },
];
